name: "Build Pull Request"
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - uses: gradle/gradle-build-action@v3
      - run: ./gradlew assembleGithubRelease

      - uses: actions/upload-artifact@v4
        with:
          name: github-${{ github.sha }}
          path: app/build/outputs/apk/github/release/*.apk